name: Check Compatibility with Examples

# Workflow triggers tell GitHub when to run the workflow:
# a) when there is a new commit on the main or develop branch
# b) when a new pull request is opened to merge a branch into main or develop
on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main", "develop"]

# This workflow defines one job: check-compatibility
jobs:
  check-compatibility:
    
    # Use ubuntu-latest runner.
    # See https://github.com/actions/runner-images for a list of available runners.
    runs-on: ubuntu-latest
    
    steps:

      # Checkout a copy of this repository on the runner
      # We use the "checkout" GitHub Action
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # Checkout a copy of the Illuminator examples repository
      - uses: actions/checkout@v4
        with:
          repository: illuminator-team/educational_material
          path: educational_material

      # - uses: conda-incubator/setup-miniconda@v3
      #   with:
      #       activate-environment: harmony
      #       auto-activate-base: false

      # - name: Create conda environment from environment.yml
      #   run: conda env update -n harmony -f environment.yml

      # A comment for this step
      - name: Test
        shell: bash -l {0}
        run: |
          pwd
          echo "----------------------- HEY --------------------"
          ls ..
          echo "----------------------- HEY --------------------"
          ls 

      # # Compile Harmony
      # - name: Compile Harmony
      #   shell: bash -l {0}
      #   run: |
      #     cd build
      #     cmake --build . --config Release 