name: Check Compatibility with Examples

# Workflow triggers tell GitHub when to run the workflow:
# a) when there is a new commit on the main or develop branch
# b) when a new pull request is opened to merge a branch into main or develop
on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main", "develop"]

# This workflow defines one job: check-compatibility
jobs:
  check-compatibility:
    
    # Use ubuntu-latest runner.
    # See https://github.com/actions/runner-images for a list of available runners.
    runs-on: ubuntu-latest
    
    steps:

      # Checkout a copy of this repository on the runner
      # We use the "checkout" GitHub Action
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # Checkout a copy of the educational_material repository
      - uses: actions/checkout@v4
        with:
          repository: illuminator-team/educational_material
          path: educational_material

      # Create conda environment called illuminator
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: illuminator
          auto-activate-base: false

      # Update illuminator conda environment with the packages from environment.yml
      - name: Create conda environment from environment.yml
        run: conda env update -n illuminator -f environment.yml

      # Uninstall the Illuminator from the environment (we want to build from source)
      - name: Uninstall Illuminator from illuminator-examples environment
        shell: bash -l {0}
        run: |
          pip freeze
          echo "--------------- HELLO ----------------"
          pip uninstall -y illuminator

      # Install the Illuminator from the current commit (build it from source)
      - name: Install the Illuminator from the current commit
        shell: bash -l {0}
        run: |
          pip freeze
          echo "--------------- HELLO ----------------"
          git status
          echo "--------------- HELLO ----------------"
          pip install .
          illuminator --version

      # # A comment for this step
      # - name: Test
      #   shell: bash -l {0}
      #   run: |

      #     pwd
      #     echo "----------------------- HEY --------------------"
      #     ls ..
      #     echo "----------------------- HEY --------------------"
      #     ls 

      # # # Compile Harmony
      # # - name: Compile Harmony
      # #   shell: bash -l {0}
      # #   run: |
      # #     cd build
      # #     cmake --build . --config Release 