name: Start docs update for website

on:
  push:
    branches:
      - feature/autoupdate_workflow
  workflow_dispatch:


jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Running workflow
        run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Illuminator-team/website/actions/workflows/documentation_build.yml/dispatches \
            -d '{"ref":"main"}'